highlighter: pygments
permalink: blogs/:title/
title: Dhaval Kapil
email: dhavalkapil@gmail.com
description: Blog of Dhaval Kapil - Developer at SDSLabs, student at IIT Roorkee
keywords: dhaval, kapil, vampire, iit roorkee, sdslabs, developer, geek, programmer, pianist, keyboardist, github, jekyll
link-description: Blog of Dhaval Kapil - Developer at <a href = 'http://team.sdslabs.co/' target = '_blank'>SDSLabs</a>, student at IIT Roorkee
baseurl: ""
url: http://dhavalkapil.github.io
