highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: Dhaval Kapil
email: me@dhavalkapil.com
description: Blog of Dhaval Kapil, graduate student at Georgia Tech
keywords: dhaval, kapil, vampire, gatech, iit, roorkee, sdslabs, security, developer, geek, programmer, pianist, github
baseurl: ""
url: https://dhavalkapil.com
name: Dhaval Kapil\'s blog
author:
  name: Dhaval Kapil
  email: me@dhavalkapil.com
